### ISSUE TITLE
Support custom code in deployed models

### ISSUE THREAD

**Issue by lukemarsden** [dotmesh-io/sklearn-flask-docker#19]
### Customer requirement
Be able to define pre- and post-processing steps that transform data on the way in and responses out of a model.

### Suggested implementation (out of date, see below)
Be able to ship a `.py` file alongside the sklearn pickled module in a well-known location. If the file exists, in this flask server, try to import a python module from it that conforms to a given interface:

```
class ICustomInference:
    def preprocess(dict) -> dict:
        pass
    def postprocess(dict) -> dict:
        pass
```

Or something similar. Then document how to test your pre- and post-processing code at model development time, and how to include it in a `ds.model()` command.

For maximum flexibility, we might also want to override the actual model inference method. (Does it make sense to enable the customer to provide the full body of the request handler? This would allow non-sklearn models to be supported via this mechanism, even.)

### Requirements.txt
For extra flexibility, support also specifying a `runtime-requirements.txt` or similar and have the requirements installed when the container is built. Ideally require that the user pins specific versions of the requirements for reproducibility.

**Comment by lukemarsden** [comment]
I talked with the user, we're going to try this: override is that you can provide the whole`predict` method.

Essentially it’s this: https://github.com/dotmesh-io/sklearn-flask-docker/blob/master/main.py#L36-L52

You drop a .py file alongside the model that conforms to some interface, and in this case, the interface would just be “can override `predict`”.

**Comment by lukemarsden** [comment]
> This would allow non-sklearn models to be supported via this mechanism, even

This latter suggestion would also enable other (non-sklearn) model types, which we have heard from another user that they would like (e.g. supporting https://radimrehurek.com/gensim/models/ldamodel.html)

**Comment by itamarst** [comment]
In order to close this issue:

* [x] Merge https://github.com/dotmesh-io/sklearn-flask-docker/pull/20
* [x] Do a new release
* [x] Do manual test (in progress)
* [ ] Make sure images get pulled to runners (https://github.com/dotmesh-io/dotscience-agent/issues/259)
* [x] If all is well, merge the PR for documentation
* [x] Release new documentation
* [x] Share documentation with interested user
* [ ] Document using non-sklearn models
* [ ] Share documentation with other interested user
* [ ] Refactor implementation so that runtime-requirements.txt is installed at image build time
